2023-04-12 18:57:14,901 : INFO : root : Loading config.
2023-04-12 18:57:14,904 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-04-12 18:57:14,905 : WARNING : ConfigProcessor : Config file in cache changed: C:\pinball\greatest_showman\config\config.yaml
2023-04-12 18:57:14,905 : INFO : ConfigProcessor : Loading config from file C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\mpfconfig.yaml.
2023-04-12 18:57:14,956 : INFO : ConfigProcessor : Loading config: C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\mpfconfig.yaml
2023-04-12 18:57:14,956 : INFO : ConfigProcessor : Loading config from file C:\pinball\greatest_showman\config\config.yaml.
2023-04-12 18:57:14,964 : INFO : ConfigProcessor : Loading config: C:\pinball\greatest_showman\config\config.yaml
2023-04-12 18:57:14,965 : INFO : ConfigProcessor : Config file cache created: C:\Users\lisas\AppData\Local\Temp\c5e3c6a6b44933afaf432493a3c7f734.mpf_cache
2023-04-12 18:57:15,036 : INFO : ConfigProcessor : Loading config from cache: C:\Users\lisas\AppData\Local\Temp\2591d1a5aee1eec0eefe4740cb1b00b0.mpf_cache
2023-04-12 18:57:15,037 : INFO : ConfigProcessor : Loading config from cache: C:\Users\lisas\AppData\Local\Temp\b5a4e895e7586a66014791409c611ae3.mpf_cache
2023-04-12 18:57:15,038 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.0
2023-04-12 18:57:15,038 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2023-04-12-18-57-14-mpf-LisaDesktop.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-04-12 18:57:15,038 : INFO : Machine : MPF path: C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf
2023-04-12 18:57:15,038 : INFO : Machine : Machine path: C:\pinball\greatest_showman
2023-04-12 18:57:15,038 : INFO : Machine : Platform: win32
2023-04-12 18:57:15,038 : INFO : Machine : Python executable location: C:\Users\lisas\.local\pipx\venvs\mpf\Scripts\python.exe
2023-04-12 18:57:15,038 : INFO : Machine : Python version: 3.9.13 (64-bit)
2023-04-12 18:57:15,039 : INFO : Machine : Initialise MPF.
2023-04-12 18:57:15,111 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,149 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-04-12 18:57:15,149 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.0', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,149 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,149 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,161 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.22621-SP0', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,161 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,161 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,161 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.22621', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,161 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2023-04-12 18:57:15,161 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-04-12 18:57:15,169 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py:118
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py:118>
Traceback (most recent call last):
  File "C:\Users\lisas\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py", line 121, in _async_handler_done
    future.result()
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\device_manager.py", line 89, in _load_device_modules
    self.load_devices_config(validate=True)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\device_manager.py", line 147, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 205, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 244, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 407, in _validate_type_machine
    return self.validation_error(item, validation_failure_info,
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 713, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry flippers:left_flipper:main_coil = "c_flipper_left_main" is not valid. Device "c_flipper_left_main" not found in "coils:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/0.56/logs/CFE-ConfigValidator-6.html)
2023-04-12 18:57:15,171 : INFO : Machine : Starting the main run loop.
2023-04-12 18:57:15,171 : INFO : Machine : Shutting down...
2023-04-12 18:57:15,171 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-04-12 18:57:16,180 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "C:\Users\lisas\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\events.py", line 121, in _async_handler_done
    future.result()
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\device_manager.py", line 89, in _load_device_modules
    self.load_devices_config(validate=True)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\device_manager.py", line 147, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 205, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 244, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 407, in _validate_type_machine
    return self.validation_error(item, validation_failure_info,
  File "C:\Users\lisas\.local\pipx\venvs\mpf\lib\site-packages\mpf\core\config_validator.py", line 713, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry flippers:left_flipper:main_coil = "c_flipper_left_main" is not valid. Device "c_flipper_left_main" not found in "coils:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/0.56/logs/CFE-ConfigValidator-6.html)
